trigger:
  branches:
    include:
      - main  # Trigger pipeline on push to main branch

variables:
  azureServiceConnection: 'YourAzureServiceConnectionName'  # Your Azure DevOps Service Connection name
  tfWorkingDirectory: '$(Build.SourcesDirectory)/terraform'
  terraformVersion: '1.0.0'

stages:


- stage: Terraform_Init
  displayName: 'Terraform Init'
  jobs:
    - job: Terraform_Init
      displayName: 'Run Terraform Init'
      pool:
        name: Default
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: $(terraformVersion)  # Specify Terraform version to install
        - script: |
            cd $(tfWorkingDirectory)
            terraform init
          displayName: 'Terraform Init'

- stage: Terraform_Plan
  displayName: 'Terraform Plan'
  condition: succeeded('Terraform_Init')  # Only run if Terraform init is successful
  jobs:
    - job: Terraform_Plan
      displayName: 'Run Terraform Plan'
      pool:
        name: Default
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: $(terraformVersion)  # Ensure Terraform is installed again for this stage
        - script: |
            terraform plan -out=tfplan  # Run terraform plan
          workingDirectory: $(tfWorkingDirectory)

- stage: Terraform_Apply
  displayName: 'Terraform Apply'
  condition: succeeded('Terraform_Plan')  # Only run if Terraform plan passes
  jobs:
    - job: Terraform_Apply
      displayName: 'Run Terraform Apply'
      pool:
        name: Default
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: $(terraformVersion)  # Ensure Terraform is installed again for this stage
        - script: |
            terraform apply -auto-approve tfplan  # Apply the Terraform plan
          workingDirectory: $(tfWorkingDirectory)
